general:
  description: Config for producing batches on for live forecasts.
  name: on_premises
input_data:
  default_forecast_minutes: 30
  default_history_minutes: 30
  #---------------------- GSP -------------------
  gsp:
    gsp_zarr_path: ./nowcasting_forecast # this is not needed
    history_minutes: 90
    metadata_only: True
    log_level: "INFO"

  #---------------------- NWP -------------------
  nwp:
    nwp_channels:
      - dswrf
    nwp_image_size_pixels: 64
    nwp_zarr_path: s3://nowcasting-nwp-development/data/latest.netcdf
#    nwp_zarr_path: ./../MetOfficeAMD/latest.netcdf
    forecast_minutes: 0
    history_minutes: 0

output_data:
  filepath: ./batches/
process:
  batch_size: 32
  seed: 1234
  upload_every_n_batches: 0 # Write directly to output_data.filepath, not to a temp directory.
  n_train_batches: 0
  n_validation_batches: 0
  n_test_batches: 0
