general:
  description: Config for producing batches on for live forecasts.
  name: mvp_v2
input_data:
  default_forecast_minutes: 120
  default_history_minutes: 30
  #---------------------- GSP -------------------
  gsp:
    gsp_zarr_path: ./nowcasting_forecast
    history_minutes: 120
    forecast_minutes: 480
    log_level: "INFO"
    is_live: True

  #---------------------- NWP -------------------
  nwp:
    nwp_channels:
      - dswrf
    nwp_image_size_pixels_height: 64
    nwp_image_size_pixels_width: 64
    nwp_zarr_path: s3://nowcasting-nwp-development/data/latest.netcdf
    forecast_minutes: 120
    history_minutes: 60

  #---------------------- Satellite -------------
  satellite:
    satellite_channels:
      - IR_016
      - IR_039
      - IR_087
      - IR_097
      - IR_108
      - IR_120
      - IR_134
      - VIS006
      - VIS008
      - WV_062
      - WV_073
    satellite_image_size_pixels_height: 24
    satellite_image_size_pixels_width: 24
    history_minutes: 60
    forecast_minutes: 0
    satellite_zarr_path: s3://nowcasting-sat-development/data/latest/latest.zarr.zip
    keep_dawn_dusk_hours: 2
    is_live: True

  #---------------------- HRVSatellite -------------
  hrvsatellite:
    hrvsatellite_channels:
      - HRV
    hrvsatellite_image_size_pixels_height: 24
    hrvsatellite_image_size_pixels_width: 24
    history_minutes: 60
    forecast_minutes: 0
    hrvsatellite_zarr_path: s3://nowcasting-sat-development/data/latest/hrv_latest.zarr.zip
    is_live: True

  #--------- PV --------
  pv:
    is_live: True
    live_interpolate_minutes: 60
    live_load_extra_minutes: 60
    forecast_minutes: 0

  sun:
    load_live: True
    elevation_limit: 0

output_data:
  filepath: ./batches/
process:
  batch_size: 32
  seed: 1234
  upload_every_n_batches: 0 # Write directly to output_data.filepath, not to a temp directory.
  n_train_batches: 0
  n_validation_batches: 0
  n_test_batches: 0
