name: Test Docker image
on: [push]

jobs:
  push_to_registry:
    name: Build docker file for testing
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Build Docker image
        run: docker-compose -f tests/test-docker-compose.yml build
      - name: Run tests inside the container
        run: docker-compose -f tests/test-docker-compose.yml run forecast

